name: Build for Windows

# Este workflow se ejecutará manualmente con workflow_dispatch
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22" # Ajusta la versión de Node.js según tu necesidad

      - name: Install dependencies
        run: npm install

      - name: Run build:win
        run: npm run build:win

      # Subir artefactos para Windows
      - name: Upload Windows MSI
        uses: actions/upload-artifact@v4
        with:
          name: pos-cevichon-installer
          path: build/windows/pos-cevichon-electron\ 1.0.0.msi

      # Subir artefactos para Windows
      - name: Upload Windows .EXE
        uses: actions/upload-artifact@v4
        with:
          name: pos-cevichon
          path: build/windows/pos-cevichon-electron\ 1.0.0.exe
