name: Build for All platforms

# Este workflow se ejecutará manualmente con workflow_dispatch
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22" # Ajusta la versión de Node.js según tu necesidad

      - name: Install dependencies
        run: npm install

      - name: Run build:all
        run: npm run build:all

      # Subir artefactos para Windows
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifact
          path: build/windows/pos-cevichon-electron\ 1.0.0.msi

      # Subir artefactos para Mac
      - name: Upload Mac Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-artifact
          path: build/mac/pos-cevichon-electron\ 1.0.0

      # Subir artefactos para Linux
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifact
          path: build/linux/pos-cevichon-electron\ 1.0.0
