name: Build for All platforms

# Este workflow se ejecutará manualmente con workflow_dispatch
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22" # Ajusta la versión de Node.js según tu necesidad

      - name: Install dependencies
        run: npm install

      - name: Run build:all
        run: npm run build:all

      - name: List generated files
        run: ls -R ./build/linux/
      - name: List generated files
        run: ls -R ./build/mac/
      - name: List generated files
        run: ls -R ./build/windows/

      - name: Upload Linux AppImage
        uses: actions/upload-artifact@v4
        with:
          name: pos-cevichon-installer
          path: ./build/linux/*.appimage

      - name: Upload MacOs DMG
        uses: actions/upload-artifact@v4
        with:
          name: pos-cevichon-installer
          path: ./build/mac/*.dmg

      # Subir artefactos para Windows MSI sin importar la versión
      - name: Upload Windows MSI
        uses: actions/upload-artifact@v4
        with:
          name: pos-cevichon-installer
          path: ./build/windows/*.msi # Encuentra cualquier archivo MSI en la carpeta

      # Subir artefactos para Windows .EXE sin importar la versión
      - name: Upload Windows .EXE
        uses: actions/upload-artifact@v4
        with:
          name: pos-cevichon
          path: ./build/windows/*.exe # Encuentra cualquier archivo EXE en la carpeta

